## Use the files generated by '2_create_merge_sample_files.sh' to merge
## biological replicates of each genotype

mkdir ./temperate/merged/
while read geno
do
    samtools merge ./temperate/merged/${geno}_merged.bam -b ./temperate/sample_lists/${geno}_samples.txt &
done < temperate_inbreds.txt

mkdir ./tropical/merged/
while read geno
do
    samtools merge ./tropical/merged/${geno}_merged.bam -b ./tropical/sample_lists/${geno}_samples.txt &
done < tropical_inbreds.txt

## Index merged BAM files
while read geno
do
    samtools index -b ./temperate/merged/${geno}_merged.bam &
done < temperate_inbreds.txt

while read geno
do
    samtools index -b ./tropical/merged/${geno}_merged.bam &
done < tropical_inbreds.txt
